### ISSUE TITLE
Set optimization strategy across multiple image types

### ISSUE THREAD

**Issue by jahrichie** [janfoeh/paperclip-optimizer#10]
Sorry to submit an issue for this, but Is there a way  to set a strategy argument  across jpg, jpeg, and png?  

Right now i'm using the below config for png, and its optimizing nicely, but i'd like to be able to upload a more diverse mime type.  

```Ruby
      :home_page_thumb => {
         :geometry => "216x223#",
         :paperclip_optimizer => {
           :pngout => {
             :strategy => 1
           }
         },
      },
```

**Comment by janfoeh** [comment]
2.0.0 is now out.
