### ISSUE TITLE
Optimize even the original image uploaded

### ISSUE THREAD

**Issue by chirag7jain** [janfoeh/paperclip-optimizer#18]
the gem currently only provides ways to optimize the styles aka (thumbnail, small large, xyz).

how can I use the gem to optimize even the original image

**Comment by janfoeh** [comment]
I'm afraid you can't — Paperclip does not call processors like paperclip-optimizer on the original. It leaves it untouched, so that should you add or change styles in the future, you can reprocess existing attachments.
