### ISSUE TITLE
Option quality does not affect the result

### ISSUE THREAD

**Issue by thebravoman** [janfoeh/paperclip-optimizer#19]
No matter how I set the value of quality the result images has the same size.

This is the model
has_attached_file :picture, styles: {
		p169: "300x169",
		p1080: "1920x1080",
		processors: [:thumbnail,:paperclip_optimizer],
		paperclip_optimizer: {
			jpegtran: { :progressive=>true },
			jpegrecompress: { :quality => 0}
    }
}

This is paperclip_optimizer.rb 
Paperclip::PaperclipOptimizer.default_options = {
  skip_missing_workers: true,
  advpng: false,
  gifsicle: false,
  jhead: true,
  jpegoptim: true,
  jpegrecompress: true,
  jpegtran: true,
  optipng: true,
  pngcrush: false,
  pngout: false,
  pngquant: false,
  svgo: false
}

Setting jpegrecompress: { :quality => 0} and jpegrecompress: { :quality => 3}
produces the same result. 

Is optimizer even enabled?

**Comment by janfoeh** [comment]
Try adding `verbose: true` to your options. Afterwards, you should find a message from PO in your Rails log for every optimized file, as well as additional messages from the underlying ImageOptim library.

**Comment by thebravoman** [comment]
Absolutely nothing happens. This is the only log I get connected with paperclip_optimizer

[paperclip] saving /episodes/pictures/000/000/338/processors/rubber-bands-lego-robot-attachment-triggered-with-a-motor-part-2-removing-the-motor_1080p.paperclip_optimizer
[AWS S3 200 2.46459 0 retries] put_object(:acl=>:public_read,:bucket_name=>"fllcasts-development",:content_length=>861636,:content_type=>"image/jpeg",:data=>Paperclip::FileAdapter: 9f732b7f26332edf0a0a7daf01e301bf20150627-14481-124x2xg.paperclip_optimizer,:key=>"episodes/pictures/000/000/338/processors/rubber-bands-lego-robot-attachment-triggered-with-a-motor-part-2-removing-the-motor_1080p.paperclip_optimizer")  

And thats it. How could I even tell if paperclip-optimizer is running\?

**Comment by thebravoman** [comment]
Figured it out. The processor option was added in the styles and it should be outside of the styles, of course.

**Comment by janfoeh** [comment]
That helps, yes :) Glad you figured it out.
