### ISSUE TITLE
image_optim_bin doesn't seem to work anymore

### ISSUE THREAD

**Issue by nemile** [janfoeh/paperclip-optimizer#21]
Hi,
I'm working on a Rails 4.1 heroku app and we are optimizing some of our images, so I installed the paperclip_optimizer gem. It works great when you have all the image_optim binaries on local, but the image_optim_bin gem seems to have some issues (https://github.com/mooktakim/image_optim_bin/issues/7). I tried this gem both on local (linux machine) and on a test heroku app, I ran both times into the same errors described on the issue link.
A workaround is to use the image_optim_pack gem (https://github.com/toy/image_optim). It worked both on local and the test herokuapp.
Here is my Gemfile:

```
gem 'paperclip'
gem 'image_optim_pack', '~> 0.2.1.20150525'
gem 'paperclip-optimizer', '~> 2.0.0'
```

Hope this helps, maybe you should update the Readme file ?

**Comment by janfoeh** [comment]
Thanks for the info Emile! I'll update the README later today as soon as I got a minute to spare.

**Comment by raarellano** [comment]
Had a similar issue. I was trying to run `rails generate paperclip_optimizer:install` and it generated the following error: `Could not find generator 'paperclip_optimizer:install'`

Including the `gem 'image_optim_pack' ` solved the problem for me. I am using Rails 4.2 and Ruby 2.1.

Thanks @nemile!

**Comment by reidcooper** [comment]
Bump, cannot deploy to heroku anymore

**Comment by janfoeh** [comment]
Hey @reidcooper, I'm not the maintainer of these gems and have no special knowledge about them. Please contact the respective projects if you're running into issues with your optimizer binaries.

**Comment by wilwade** [comment]
https://github.com/toy/image_optim_pack also worked for me.
