### ISSUE TITLE
ImageOptim::BinResolver::Error when creating new attachment.

### ISSUE THREAD

**Issue by danielbonnell** [janfoeh/paperclip-optimizer#22]
Hi, I just installed version 2.0.0 and I'm encountering the following bug. 

    ImageOptim::BinResolver::Error - Bin resolving errors:
    pngout worker: `pngout` not found; please provide proper binary or disable this worker (--no-pngout argument or `:pngout => false` through options)
    jpegrecompress worker: `jpeg-recompress` not found; please provide proper binary or disable this worker (--no-jpegrecompress argument or `:jpegrecompress => false` through options)
    svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options):

I'm not sure if its a bug or if my configuration is wrong. In `application.rb` I have `config.assets.image_optim = false`.
In my initializer I have:

    Paperclip::PaperclipOptimizer.default_options = {
        skip_missing_workers: true,
        advpng: false,
        gifsicle: false,
        jhead: false,
        jpegoptim: false,
        jpegrecompress: true,
        jpegtran: false,
        optipng: false,
        pngcrush: false,
        pngout: false,
        pngquant: true,
        svgo: false
    }

And in my model I have:
```has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "", processors: [:thumbnail, :paperclip_optimizer]```

**Comment by janfoeh** [comment]
Hi Daniel,

I suspect this might be the source of your troubles: https://github.com/janfoeh/paperclip-optimizer#caution

Can you try disabling ImageOptim for the asset pipeline as described there?

**Comment by danielbonnell** [comment]
Hi janfoeh,

I just realized my mistake and it was a real obvious one at that. In my initializer I had uncommented both `default_options` hashes and forgot to merge them into a single options hash. So my second hash was overriding the first. I merged them and the problem went away.

Thanks!

**Comment by janfoeh** [comment]
Great to hear you fixed it!

Cheers - Jan
