### ISSUE TITLE
jpegrecompress worker: `jpeg-recompress` not found;

### ISSUE THREAD

**Issue by danielbonnell** [janfoeh/paperclip-optimizer#23]
Sorry to open another issue so soon, but I'm having trouble with the jpeg-recompress binary. I'm very new to this and am not sure if it's a bug or if I'm missing something. I encounter the error in the title when attempting to save an image that I uploaded. I went to the jpeg-archive project's page and followed the instructions for installing it using `brew install mozjpeg`, but that didn't solve my issue. I haven't been able to find any resources on the problem.

Thanks!

**Comment by janfoeh** [comment]
If you run `which jpeg-recompress`, it'll probably not give you any results, because it's not installed. I believe you need to install it with

    brew install jpeg-archive

**Comment by danielbonnell** [comment]
When I run `brew install jpeg-archive` it errors:
    ➜  bin git:(master) brew install jpeg-archive
    Error: No available formula for jpeg-archive
    Searching formulae...
    Searching taps...

**Comment by janfoeh** [comment]
`brew search jpeg-archive` works for me; try running `brew update` beforehand.

**Comment by danielbonnell** [comment]
Running `brew update` worked. Got the binaries installed and I'm not hitting any errors now. When I check the file size of the uploaded image against the original though, there is no difference. In the settings hash I have the `quality` setting for `jpegcompress` set to 2, so I would expect some compression.

**Comment by janfoeh** [comment]
With that I'm afraid I can't help; I only run `jpegtran` and `optipng` in production. Sorry!

**Comment by danielbonnell** [comment]
No worries. Thanks for your help with this though!
