### ISSUE TITLE
Compatibility with Paperclip 5.x?

### ISSUE THREAD

**Issue by julitrows** [janfoeh/paperclip-optimizer#28]
The Readme states this gem is compatible with Paperclip 3 and 4. Has it been tested on paperclip 5? Any plans on it bringing up?

**Comment by janfoeh** [comment]
Hey @jantequera ,

I haven't looked at 5 yet, as none of my current projects have anything to do with images. I have a couple of legacy projects which still use 4; if I find the time to update them, I'll take a look, but I can't promise any timeframe for this.

Cheers,
Jan

**Comment by dgilperez** [comment]
Any updates on this? Someone using this gem with 5.x?

**Comment by janfoeh** [comment]
PaperclipOptimizer is now EOL.

For maintained alternatives, have a look at https://github.com/kreeti/kt-paperclip and https://github.com/loco2/kt-paperclip-optimizer .
