### ISSUE TITLE
mimemagic issues - a resolution

### ISSUE THREAD

**Issue by reedstonefood** [janfoeh/paperclip-optimizer#31]
This gem will no longer install; this is because it relies on paperclip, which relies on a [yanked version of the mimemagic gem](https://github.com/mimemagicrb/mimemagic/issues/98). [Paperclip is deprecated](https://github.com/thoughtbot/paperclip#deprecated) and thus we do not anticipate a change being made to it to get around the yanked gem.

We at [loco2](https://github.com/loco2/) use this gem, so to prevent deployments being broken we have [forked this repository](https://github.com/loco2/kt-paperclip-optimizer) and published the [kt-paperclip-optimizer gem](https://rubygems.org/gems/kt-paperclip-optimizer) for anyone to use. Instead of using paperclip, it uses the maintained fork [kt-paperclip](https://github.com/kreeti/kt-paperclip) which we switched to last year. kt-paperclip doesn't yet have a fix for the mimemagic issue, but we anticipate it will [shortly](https://github.com/kreeti/kt-paperclip/pull/54).

@janfoeh we were unsure if you would want to make these changes to your gem so in the interests of getting our pipelines fixed we went ahead and forked it, we mean no disrepect & will happily switch back if you want to make these changes to your gem.

**Comment by janfoeh** [comment]
Hey there,

apologies for the late reply, and thanks for the heads-up!

I've been somewhat unsure about how to EOL this gem properly. If your fork gives it a new lease on life, that's great!

Would it be sufficient for you if I added a prominent note to the README to direct people towards your repository? I'd then archive it afterwards.

**Comment by reedstonefood** [comment]
Thanks for the reply @janfoeh . We've discussed this internally and agree that your proposal sounds fine to us. 👍 

It might be helpful for folks if you mention that `paperclip` is deprecated and `kt-paperclip` is the successor, or add a link to this issue.

**Comment by janfoeh** [comment]
Done!
