### ISSUE TITLE
Default Setting suggestion.

### ISSUE THREAD

**Issue by braindeaf** [janfoeh/paperclip-optimizer#6]
Hi there,

I wanted to raise that, DEFAULT_SETTINGS can either be set on each individual style or  use the overall defaults. Since you can't override DEFAULT_SETTINGS. Ok, you can but you get an error when modifying an existing constant. I was going to suggest that it might be appropriate to set another way of changing the defaults. Since image_optim requires you to set Rails.application.config.assets.image_optim in order to define which binaries to use / configure and which to switch off. I was going to suggest mirroring those settings 

Rails.application.config.paperclip_optomizer.image_optim = Rails.application.config.assets.image_optim 

or allowing them to be set manually.

Rails.application.config.paperclip_optomizer.image_optim = {:jpegoptim => true}

Our particular deployment is using Gentoo and we are restricted to only using what we can install on the remote server.

Happy to create a patch if any of this sounds appropriate. All the best

RobL

**Comment by janfoeh** [comment]
2.0.0 is now out.

**Comment by danielbonnell** [comment]
Hi, I just installed 2.0.0 and I'm still encountering this problem. I'm not sure if its a bug or if my configuration is wrong. In `application.rb` I have `config.assets.image_optim = false`.
In my initializer I have:
```Paperclip::PaperclipOptimizer.default_options = {
    skip_missing_workers: true,
    advpng: false,
    gifsicle: false,
    jhead: false,
    jpegoptim: false,
    jpegrecompress: true,
    jpegtran: false,
    optipng: false,
    pngcrush: false,
    pngout: false,
    pngquant: true,
    svgo: false
}
```
And in my model I have:
```has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "", processors: [:thumbnail, :paperclip_optimizer]```
